name: Run Cucumber Tests with TestNG

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  verify-java:
    runs-on: ubuntu-latest

    steps:
      - name: Check Java versions
        run: |
          java -version  # Prints the currently available Java version
          update-alternatives --list java  # Lists available Java alternatives

  test:
    runs-on: ubuntu-latest  # Choose the runner environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Set up JDK (OpenJDK)
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Set your desired Java version
          distribution: 'openjdk'  # Use OpenJDK as a fallback

      - name: Install Dependencies
        run: |
          mvn clean install  # Use Maven to install dependencies and build the project

      - name: Run Cucumber Tests
        run: |
          mvn test -Dcucumber.options="--tags @smoke"  # You can customize the tag or test filtering
